# Setup
title:        Stephen Hage's Data Science Site
tagline:      A collection of my data science projects
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Stephen Hage
  url:        https://stephenhage.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown


theme: jekyll-theme-cayman