# Setup
title:        Stephen Hage's Data Science Site
tagline:      A collection of my data science projects
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Stephen Hage
  url:        https://stephenhage.github.io

# Gems
gems:
  - jekyll-paginate
  - jekyll-default-layout

#Others
markdown: kramdown

# Plugins
plugins:
  - jekyll-default-layout

remote_theme: "mmistakes/minimal-mistakes@4.14.1"
permalink: /projects/:year/:month/:day/:title
